### ISSUE TITLE
P87 两处错误

### ISSUE THREAD

**Issue by hrban** [NickleHuang/Deep-Understanding-Of-Java-High-Concurrency-Programming-Corrigendum#4]
P87 两个错误 
1. 获取写锁流程中，图中的两处应当是原子性加 0xffff0001，而不是减
![微信图片_20211128111931](https://user-images.githubusercontent.com/40195878/143727538-90f4ddc7-b99c-4778-837c-ec9f849017cb.jpg)

2.在释放写锁流程中，在jnz 2f处的注释 比较的不是之前的count值，而是相加后的值 如图
![微信图片_20211128112204](https://user-images.githubusercontent.com/40195878/143727625-ad4a1fe3-f74b-4ea9-9123-c169a321193a.jpg)

**Comment by NickleHuang** [comment]
已经修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月28日(周日) 中午11:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [NickleHuang/Deep-Understanding-Of-Java-High-Concurrency-Programming-Corrigendum] P87 两处错误 (Issue #4)




 
P87 两个错误
  
获取写锁流程中，图中的两处应当是原子性加 0xffff0001，而不是减
  
 
2.在释放写锁流程中，在jnz 2f处的注释 比较的不是之前的count值，而是相加后的值 如图
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NickleHuang** [comment]
看项目的md修复描述



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月28日(周日) 中午11:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [NickleHuang/Deep-Understanding-Of-Java-High-Concurrency-Programming-Corrigendum] P87 两处错误 (Issue #4)




 
P87 两个错误
  
获取写锁流程中，图中的两处应当是原子性加 0xffff0001，而不是减
  
 
2.在释放写锁流程中，在jnz 2f处的注释 比较的不是之前的count值，而是相加后的值 如图
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
